monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event"]
            # uncomment to get logging in your browser
            # you may have to allow bigger header sizes in your Web server configuration
            # firephp:
            #    type: firephp
            #    level: info
            # chromephp:
            #    type: chromephp
            #    level: info
            # console:
            #     type: console
            #     process_psr_3_messages: false
            #     channels: ["!event", "!doctrine", "!console"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: info
                handler: grouped
            grouped:
                type: group
                members: [ streamed, deduplicated ]
            streamed:
                type: rotating_file
                path: '%kernel.logs_dir%/%kernel.environment%.log'
                level: info
                max_files: 15
            deduplicated:
                type: deduplication
                handler: symfony_mailer
            symfony_mailer:
                type: symfony_mailer
                from_email: 'carolin.salloum@gmail.com'
                to_email: 'carolin.salloum@gmail.com'
                subject: 'Ajroudsoftwares, An Error Occurred! %%message%%'
                level: critical
                formatter: monolog.formatter.html
                content_type: text/html