<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => 'be9e18177724af972e1633133db81862',
  'DATABASE_URL' => 'mysql://root:@127.0.0.1:3306/monprojetfinal',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
  'MAILER_DSN' => 'smtp://info@francoarabophone.fr:Caro1Firas0251123@smtp.ionos.fr:465?encryption=ssl',
  'JWT_SECRET' => 'Tarbouche1986Salloum',
);
